on:
  workflow_run:
    workflows:
      - "macos-build-test.yml"
      - "windows-build-test.yml"
      - "linux-build-test.yml"
    types:
      - completed
  push:
    branches:
      - main
name: combined-release-workflow

env:
  GH_TOKEN: ${{ github.token }}
  Repo: "sargeantPig/RTWLibTools"

jobs:
  combined-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
      
      - name: Wait for 2 minutes
        run: |
          sleep 120  # Sleep for 2 minutes (2 minutes * 60 seconds/minute)
        shell: bash

      - name: Publish Windows Build
        if: ${{ steps.release.outputs.release_created }}
        run: dotnet publish ${{github.workspace}}/RTWLib_CLI/RTWLib_CLI.csproj -c Release -r win-x64 --self-contained true -o ./publish/win-x64
      
      - name: Publish Windows Artifact
        uses: actions/upload-artifact@v2
        with:
          name: RTWRand-windows
          path: ${{github.workspace}}/publish/win-x64

      - name: Publish macOS Build
        if: ${{ steps.release.outputs.release_created }}
        run: dotnet publish ${{github.workspace}}/RTWLib_CLI/RTWLib_CLI.csproj -c Release -r osx-x64 --self-contained true -o ./publish/osx-x64
  
      - name: Publish macOS Artifact
        uses: actions/upload-artifact@v2
        with:
          name: RTWRand-macos
          path:  ${{github.workspace}}/publish/osx-64

      - name: Publish Linux Build
        if: ${{ steps.release.outputs.release_created }}
        run: dotnet publish ${{github.workspace}}/RTWLib_CLI/RTWLib_CLI.csproj -c Release -r linux-x64 --self-contained true -o ./publish/linux-x64
  
      - name: Publish linux Artifact
        uses: actions/upload-artifact@v2
        with:
          name: RTWRand-linux
          path:  ${{github.workspace}}/publish/linux-x64
      
      
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload ${{ steps.release.outputs.tag_name }} ./artifact/some-build-artifact.zip
      
