name: Upload Release Artifacts

on:
  release:
    types:
      - published

jobs:
  upload-release-artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Release Tag
      id: get-release-tag
      run: |
        release_tag="${{ github.event.release.tag_name }}"
        echo "Uploading artifacts to release with tag: $release_tag"
      shell: bash

    - name: Upload Release Artifacts
      run: |
        release_tag="${{ steps.get-release-tag.outputs.release_tag }}"
        # Use the release tag to determine which release to upload to
        # Add the necessary commands for uploading artifacts
      shell: bash
